<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Tentang Kami</title>';
echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">';
echo '</head>';
echo '<body>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark">';
echo '<!-- Navbar content -->';
echo '</nav>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark">';
echo '<a class="navbar-brand" href="#">CoffeShop</a>';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarNav">';
echo '<ul class="navbar-nav ml-auto">';
echo '<li class="nav-item active">';
echo '<a class="nav-link" href="website.php">Beranda</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="tentangkami.php">Tentang Kami</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="menu.php">Menu</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="kontak.php">Kontak</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="container my-5">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<h2>Tentang Kami</h2>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<img src="usercewek.jpeg" alt="Foto Profil" class="img-fluid rounded-circle mb-3">';
echo '<p><strong>Nama:</strong> Nur Ariska </p>';
echo '<p><strong>NIM:</strong> 220209502127 </p>';
echo '<p><strong>Kelas:</strong> PTIK F</p>';
echo '<h4>Riwayat Pendidikan</h4>';
echo '<ul>';
echo '<li>SD : SD NEGERI 77 PINRANG<br>';
echo 'SMP : SMPS PPM RAHMATUL ASRI<br>';
echo 'SMA : SMK NEGERI 1 PINRANG<br>';
echo 'INSTANSI : UNIVERSITAS NEGERI MAKASSAR</li>';
echo '<!-- Tambahkan riwayat pendidikan sesuai kebutuhan -->';
echo '</ul>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<img src="usercewek.jpeg" alt="Foto Profil" class="img-fluid rounded-circle mb-3">';
echo '<p><strong>Nama:</strong> Nayla zhaffa </p>';
echo '<p><strong>NIM:</strong> 220209502127</p>';
echo '<p><strong>Kelas:</strong> PTIK F</p>';
echo '<h4>Riwayat Pendidikan</h4>';
echo '<ul>';
echo '<li>SD : SD NEGERI 265 TIMAMPU<br>';
echo 'SMP : SMP NEGERI 1 LUWU TIMUR<br>';
echo 'SMA : SMA NEGERI 17 MAKASSAR<br>';
echo 'INSTANSI : UNIVERSITAS NEGERI MAKASSAR</li>';
echo '<!-- Tambahkan riwayat pendidikan sesuai kebutuhan -->';
echo '</ul>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<img src="usercewek.jpeg" alt="Foto Profil" class="img-fluid rounded-circle mb-3">';
echo '<p><strong>Nama:</strong> Muthiah Nurul Hidayah</p>';
echo '<p><strong>NIM:</strong> 220209502117</p>';
echo '<p><strong>Kelas:</strong> PTIK F</p>';
echo '<h4>Riwayat Pendidikan</h4>';
echo '<ul>';
echo '<li>SD : SDIT BINAUL UMMAH MALUK <br>';
echo 'SMP : SMPIT AL BIRUNI MAKASSAR <br>';
echo 'SMA : SMAIT AL BIRUNI MAKASSAR<br>';
echo 'INSTANSI : UNIVERSITAS NEGERI MAKASSAR</li>';
echo '<!-- Tambahkan riwayat pendidikan sesuai kebutuhan -->';
echo '</ul>';
echo '</div>';
echo '<br>';
echo '<div class="col-lg-4">';
echo '<img src="usercowok.jpeg" alt="Foto Profil" class="img-fluid rounded-circle mb-3">';
echo '<p><strong>Nama:</strong> Muqinuddin Baso Mattappa </p>';
echo '<p><strong>NIM:</strong> 220209502114 </p>';
echo '<p><strong>Kelas:</strong> PTIK F </p>';
echo '<h4>Riwayat Pendidikan</h4>';
echo '<ul>';
echo '<li>SD : SDN KOMPLEK IKIP<br>';
echo 'SMP : SMPN 3 MAKASSAR<br>';
echo 'SMA : SMA BUDI UTOMO PERAK JOMBANG<br>';
echo 'INSTANSI : UNIVERSITAS NEGERI MAKASSAR</li>';
echo '<!-- Tambahkan riwayat pendidikan sesuai kebutuhan -->';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<footer class="bg-dark text-white text-center py-3">';
echo '<p>&copy; 2023 CoffeShop</p>';
echo '</footer>';
echo '';
echo '<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>